name: Trance_End
favicon: null
layout_spectrum: 0.1496578890364617
typography_spectrum: 0.18495869892649353
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7218068807851523
  lightness: 0.136569150025025
  saturation: 0.48648548242636025
  rhythmicContrast: 0.2848319010809064
purpose: []
